# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d8c2c9047435f0c81dda35c58dac116ae495211de2823de19828a93e5634c768abe9c862d86d83e779040674d83f82d5e32ea46b05c1fa7618ad7bac100385c

test:
  secret_key_base: a2ab2cad5dbacaeabac2a10da171c4d2f778203a91e56a3fb57010f4c13bb5d7ed2c0999318c917aa144c580c647f359ed718c6d6b702bee7c5e3ccbad114c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
